### ISSUE TITLE
changes to sizes of steps and sticky

### ISSUE THREAD

**Issue by newskwasi** [jsoma/simplified-scrollama-scrollytelling#1]
using sticky side and i was wanted to know how to change the size of the steps, horizontally, so I can have more words and not let it be too thin. i would like then for the photos to be resized and then show fully even if its smaller. i tried to use background size: contain and centre and i tried some numbers but it doesn't change anything or it creates a collage.

**Comment by jsoma** [comment]
Ah, I know the collage! You got close with your `background-size` and your centering but you need a couple more pieces:

```css
background-size: contain;
background-position: center center;
background-repeat: no-repeat;
```

I think you can also make your text a little bit smaller to fit more text in.

To make the sticky vs column change size:

![html](https://user-images.githubusercontent.com/95126/128177319-1a2a3da3-a1a3-4617-a61d-a26f0cc8b1bd.png)

it's two divs next to each other, `article` and `.sticky-thing`. They are both `flex: 1;` which means they are evenly spaced out, but by default the `article` has a `max-width: 20rem;` which means it can't get bigger than a certain amount, so the `.sticky-thing` expands to fill the rest of the space.

![styles for .article](https://user-images.githubusercontent.com/95126/128176990-e0f2408f-4572-4dde-92da-0f82c7993730.png)

If instead you set up `max-width` to  be on `.sticky-thing` you'll be able to get what you're looking for!

![larger text compared to sticky](https://user-images.githubusercontent.com/95126/128177122-be715898-85b2-42b4-bed5-633011d1dab1.png)
